// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "Clipboard": Application Resource Href Factories
//
// Command:
// $ goagen
// --design=sebs.software\Malangelus\Clipboard\design
// --out=$(GOPATH)\src\sebs.software\Malangelus\Clipboard
// --version=v1.3.1

package app
