// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "Clipboard": Application Media Types
//
// Command:
// $ goagen
// --design=sebs.software\Malangelus\Clipboard\design
// --out=$(GOPATH)\src\sebs.software\Malangelus\Clipboard
// --version=v1.3.1

package app

// ClipboardRetrieve media type (default view)
//
// Identifier: application/vnd.clipboard.retrieve; view=default
type ClipboardRetrieve struct {
	Value *string `form:"value,omitempty" json:"value,omitempty" yaml:"value,omitempty" xml:"value,omitempty"`
}

// ClipboardStore media type (default view)
//
// Identifier: application/vnd.clipboard.store; view=default
type ClipboardStore struct {
	GUID *string `form:"guid,omitempty" json:"guid,omitempty" yaml:"guid,omitempty" xml:"guid,omitempty"`
}
